(()=>{
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const storage={get(k,f=''){try{return localStorage.getItem(k)??f}catch(_){return f}},set(k,v){try{localStorage.setItem(k,v)}catch(_){}},remove(k){try{localStorage.removeItem(k)}catch(_){}}};
  const practiceFiles=['prakticke-pocitani.html','logika-mnoziny.html','mocniny.html','algebraicke-vyrazy.html','funkce.html','kvadraticke.html','soustavy.html','exp-log-funkce.html','exp-log-rovnice.html','goniometrie.html','gon-vzorce.html','posloupnosti.html','planimetrie.html','stereometrie.html','analyticka-geometrie-rovina.html','kombinatorika-pravdepodobnost.html','absolutni-hodnoty.html'];
  function practiceDone(){let n=0;try{practiceFiles.forEach(f=>n+=Object.keys(JSON.parse(storage.get(`maturita-cermat-xp:${f}`,'{}'))).length)}catch(_){}return n}
  function testStarted(){try{if(Object.values(JSON.parse(storage.get('maturita-test-attempts-v1','{}'))).some(Boolean))return true}catch(_){}return ['maturita-test-1-best','maturita-test-2-best','maturita-simulace-1-best','maturita-simulace-2-best'].some(k=>Number(storage.get(k,'0'))>0)}
  function stepStates(){return [Boolean(storage.get('maturita-diagnostika-score')),Boolean(storage.get('maturita-plan-hotov')),practiceDone()>0,testStarted()]}
  function renderSteps(){const states=stepStates();$$('.flow-step').forEach((el,i)=>{el.classList.toggle('done',states[i]);const state=el.querySelector('.state');if(state)state.textContent=states[i]?'✓':''});const done=$('#flow-done');if(done)done.textContent=`Zahájené kroky: ${states.filter(Boolean).length} ze 4`}
  renderSteps();
  if(document.body.dataset.page==='hub'){
    const done=practiceDone(), score=storage.get('maturita-diagnostika-score');
    const diag=$('#hub-diag'); if(diag)diag.textContent=score!==''?`${score} z 22 správně`:'zatím nevyplněná';
    const practice=$('#hub-practice'); if(practice)practice.textContent=`${done} ze 114 úloh bez nápovědy`;
    const tests=$('#hub-tests'); if(tests)tests.textContent=testStarted()?'alespoň jeden test dokončen':'zatím bez výsledku';
  }
  if(document.body.dataset.page==='diagnostika'){
    const questions=$$('.diag-question'),count=$('#diag-count'),bar=$('#diag-progress'),result=$('#diag-result');
    const answers=['b','b','b','a','b','a','c','a','a','b','b','c','a','b','c','c','a','b','11','40','2','3/10|0.3'];
    const recommendations={cisla:['Procenta, poměr a jednotky','prakticke-pocitani.html'],vyrazy:['Algebraické a lomené výrazy','algebraicke-vyrazy.html'],rovnice:['Rovnice a nerovnice','funkce.html#obory-rce'],funkce:['Funkce a grafy','funkce.html'],planimetrie:['Planimetrie','planimetrie.html'],stereometrie:['Stereometrie','stereometrie.html'],analytika:['Analytická geometrie','analyticka-geometrie-rovina.html'],posloupnosti:['Posloupnosti','posloupnosti.html'],pravdepodobnost:['Kombinatorika a pravděpodobnost','kombinatorika-pravdepodobnost.html']};
    try{const saved=JSON.parse(storage.get('maturita-diagnostika-v2','{}'));Object.entries(saved).forEach(([name,value])=>{const text=$(`input[name="${name}"][type="text"]`);if(text)text.value=value;else{const input=$$(`input[name="${name}"]`).find(i=>i.value===value);if(input)input.checked=true}})}catch(_){}
    const normalize=v=>String(v||'').trim().toLocaleLowerCase('cs').replace(/\s+/g,'').replace(',','.');
    const selected=()=>Object.fromEntries(questions.map((q,i)=>{const input=q.querySelector('input:checked, input[type="text"]');return[`d${i+1}`,input?input.value:'']}));
    function update(){const values=selected(),n=Object.values(values).filter(Boolean).length;count.textContent=`${n} z ${questions.length} zodpovězeno`;bar.style.width=`${n/questions.length*100}%`;storage.set('maturita-diagnostika-v2',JSON.stringify(values))}
    $$('#diag-questions input').forEach(i=>{i.addEventListener('change',update);if(i.type==='text')i.addEventListener('input',update)});
    $('#diag-submit').addEventListener('click',()=>{const values=selected(),missing=Object.values(values).filter(v=>!v).length;if(missing){result.innerHTML=`<strong>Ještě chybí ${missing} ${missing===1?'odpověď':missing<5?'odpovědi':'odpovědí'}.</strong> Můžeš je doplnit, nebo krok přeskočit.`;return}const wrong=questions.filter((q,i)=>!answers[i].split('|').map(normalize).includes(normalize(values[`d${i+1}`]))),score=questions.length-wrong.length;storage.set('maturita-diagnostika-score',String(score));if(!wrong.length){result.innerHTML=`<strong>${score} z ${questions.length} správně.</strong> Základy vypadají dobře. <a href="maturita-plan.html">Pokračuj studijním plánem →</a>`}else{const counts=wrong.reduce((a,q)=>(a[q.dataset.topic]=(a[q.dataset.topic]||0)+1,a),{}),order=Object.entries(counts).sort((a,b)=>b[1]-a[1]).map(([t])=>t),links=order.slice(0,4).map((t,i)=>`<a href="${recommendations[t][1]}">${i+1}. ${recommendations[t][0]}</a>`).join(' · ');storage.set('maturita-slabiny',JSON.stringify(order));result.innerHTML=`<strong>${score} z ${questions.length} správně.</strong> Doporučené pořadí: ${links}.<br><br><a href="maturita-plan.html">Pokračovat na studijní plán →</a>`}renderSteps();result.scrollIntoView({behavior:'smooth',block:'center'})});
    $('#diag-reset').addEventListener('click',()=>{$$('#diag-questions input').forEach(i=>i.type==='radio'?i.checked=false:i.value='');storage.remove('maturita-diagnostika-v2');storage.remove('maturita-diagnostika-score');result.textContent='Odpověz na úlohy a potom diagnostiku vyhodnoť.';update();renderSteps()});update();
  }
  if(document.body.dataset.page==='plan'){
    const input=$('#exam-date'),output=$('#date-plan-result'),cards=$$('.plan-card');const now=new Date(),local=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;input.min=local(now);input.value=storage.get('maturita-datum-zkousky');
    function render(){if(!input.value)return;const start=new Date();start.setHours(0,0,0,0);const target=new Date(`${input.value}T12:00:00`),days=Math.ceil((target-start)/86400000);cards.forEach(c=>c.classList.remove('recommended'));if(!Number.isFinite(days)||days<1){output.innerHTML='<strong>Vyber budoucí datum.</strong>';return}let i=2,text='čtyři studijní bloky týdně, z toho jeden věnuj starým chybám';if(days<=14){i=0;text='každý den 45–60 minut a obě dostupné simulace'}else if(days<=49){i=1;text='čtyři studijní bloky týdně a jednu simulaci týdně'}cards[i].classList.add('recommended');output.innerHTML=`<strong>Zbývá ${days} ${days===1?'den':days<5?'dny':'dní'}.</strong> Doporučení: ${text}.`;storage.set('maturita-datum-zkousky',input.value);storage.set('maturita-plan-hotov','1');renderSteps()}
    input.addEventListener('change',render);$('#plan-done').addEventListener('click',()=>{storage.set('maturita-plan-hotov','1')});render();
  }
  if(document.body.dataset.page==='okruhy'){
    const done=practiceDone(),count=$('#practice-count'),bar=$('#practice-bar');count.textContent=`${done} ze 114 bez nápovědy`;bar.style.width=`${Math.min(done/114*100,100)}%`;
  }
  if(document.body.dataset.page==='testy'){
    let completed={};try{completed=JSON.parse(storage.get('maturita-test-attempts-v1','{}'))}catch(_){}const keys=[['test-1-best','maturita-test-1-best',25,2,'maturita-test-1.html'],['test-2-best','maturita-test-2-best',25,2,'maturita-test-2.html'],['sim-1-best','maturita-simulace-1-best',50,1,'cermat-simulace-1.html'],['sim-2-best','maturita-simulace-2-best',50,1,'cermat-simulace-2.html']];keys.forEach(([id,key,max,mul,file])=>{const n=Number(storage.get(key,'0'));$(`#${id}`).textContent=n||completed[file]?`${n} z ${max}${mul===2?` (${n*2} bodů)`: ' bodů'}`:'zatím nespuštěno'});$('#maturita-xp').textContent=`${Number(storage.get('maturita-xp','0'))} XP`;
    const display=$('#timer-display'),start=$('#timer-start'),pause=$('#timer-pause'),reset=$('#timer-reset'),notes=$('#mistake-notes'),state=$('#notes-state'),full=135*60;let timer={remaining:full,running:false,endAt:0};try{const saved=JSON.parse(storage.get('maturita-test-timer','null'));if(saved&&Number.isFinite(saved.remaining))timer=saved}catch(_){}notes.value=storage.get('maturita-denik-chyb');const remaining=()=>timer.running?Math.max(0,Math.ceil((timer.endAt-Date.now())/1000)):timer.remaining;function persist(){storage.set('maturita-test-timer',JSON.stringify(timer))}function render(){const s=remaining();if(timer.running)timer.remaining=s;display.textContent=[Math.floor(s/3600),Math.floor(s%3600/60),s%60].map(v=>String(v).padStart(2,'0')).join(':');display.classList.toggle('finished',s===0);start.textContent=timer.running?'Běží…':s===full?'Spustit':'Pokračovat';start.disabled=timer.running||s===0;pause.disabled=!timer.running;if(!s&&timer.running){timer.running=false;persist()}}start.addEventListener('click',()=>{timer.running=true;timer.endAt=Date.now()+timer.remaining*1000;persist();render()});pause.addEventListener('click',()=>{timer.remaining=remaining();timer.running=false;persist();render()});reset.addEventListener('click',()=>{timer={remaining:full,running:false,endAt:0};persist();render()});let timeout;notes.addEventListener('input',()=>{storage.set('maturita-denik-chyb',notes.value);state.textContent='uloženo';clearTimeout(timeout);timeout=setTimeout(()=>state.textContent='',1300)});render();setInterval(render,500);
  }
})();
